spring:
  mqtt:
    domain: 127.0.0.1
    port: 1883
    clientId: SERVER00000001
    username: admin
    password: admin
    connectionTimeout: 10
    automaticReconnect: true
    cleanSession: true
    keepAliveInterval: 60

